/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 console.gltf --transform 
Files: console.gltf [56.98MB] > /Users/vincentcheong/Downloads/console/console-transformed.glb [508.25KB] (99%)
Author: ELIZION (https://sketchfab.com/ELIZION)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-retro-game-console-d672d0ac1d6a4d238314d6675f8f92b2
Title: Super Retro Game Console
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/console-transformed.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      const actionNames = Object.keys(actions);
      if (actionNames.length > 0) {
        actions[actionNames[0]].play();
      }
    }
  }, [actions]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['01_-_Default']} position={[8.88, -21.91, 5.053]} rotation={[0.604, 0.555, -0.16]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('/console-transformed.glb')
